[package]
name = "cantonese_frequency_list"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.8.0"
serde_json = "1.0.108"
dashmap = "5.5.3"
kdam = { version = "0.5.1", features = [ "rayon" ] }
aho-corasick = "1.1.2"
